spring:
  application:
    name:DesafioPotiguar
  datasource:
    url: jdbc:postgresql://db.ybpekkiimczzfbhfazjm.supabase.co:5432/postgres
    username: postgres
    password: G3YFnDFsH6mAINrO
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true

